FROM node:14.16.1-buster-slim

ENV NODE_ENV=development
# Install pm2 with Typescript
RUN npm i -g pm2 && pm2 install typescript

WORKDIR /home/node/app

# BUILD SECTION
COPY --chown=node:node package.json ecosystem.config.js yarn.lock tsconfig.json ./
COPY --chown=node:node ./src ./src
COPY --chown=node:node ./uploads ./uploads

RUN yarn

USER node

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
